### ISSUE TITLE
Run testbench fail

### ISSUE THREAD

**Issue by shanshuixiangyi** [lowRISC/ibex#1985]
``` shell
This program built for x86_64-redhat-linux-gnu
Reading makefiles...
Updating goal targets....
 File `all' does not exist.
   File `collect_results' does not exist.
     File `out/metadata/regr.log.stamp' does not exist.
         File `/test_riscv/ibex-master/ibex-master/dv/uvm/core_ibex/out/run/tests/riscv_arithmetic_basic_test.28462/rtl_sim.log' does not exist.
           File `out/metadata/tb.compile.stamp' does not exist.
             File `FORCE' does not exist.
            Must remake target `FORCE'.
            Successfully remade target file `FORCE'.
          Must remake target `out/metadata/tb.compile.stamp'.
Building RTL testbench
Traceback (most recent call last):
  File "scripts/compile_tb.py", line 75, in _main
    subprocess.check_output(['pkg-config', '--exists'] + spike_iss_pc)
  File "/usr/local/python3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/python3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pkg-config', '--exists', 'riscv-riscv', 'riscv-disasm', 'riscv-fdt']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/compile_tb.py", line 110, in <module>
    sys.exit(_main())
  File "scripts/compile_tb.py", line 77, in _main
    raise RuntimeError(
RuntimeError: Failed to find ['riscv-riscv', 'riscv-disasm', 'riscv-fdt'] pkg-config packages. Did you set the PKG_CONFIG_PATH correctly?
make[1]: *** [out/metadata/tb.compile.stamp] Error 1
```
I setted the env as follows, Path is build & make & make install path . Why scripts tell me PKG_CONFIG_PATH correctly?
``` cshell
setenv SPIKE_PATH /test_riscv/spike/bin
setenv PKG_CONFIG_PATH /test_riscv/spike/lib/pkgconfig
```

**Comment by rswarbrick** [comment]
I think that the problem here seems to be that you don't have the right path set up for pkg-config. If you're still having trouble here, it might make sense to debug things by running something like `pkg-config --path riscv-riscv`: it will spit out a path to the `.pc` file on success.

Anyway, I'm closing the issue because I don't think it points at something that needs fixing at the Ibex end.
