### ISSUE TITLE
docs/readthedocs.org:ibex-core CI step keeps failing

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/ibex#2132]
The docs/readthedocs.org:ibex-core CI steps rebuilding the documentation seems to keep failing. I've seen it for multiple PRs now. The error message we get is always:
```
 python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v4.5.0
/home/docs/checkouts/readthedocs.org/user_builds/ibex-core/envs/2130/lib/python3.11/site-packages/setuptools_scm/git.py:163: UserWarning: "/home/docs/checkouts/readthedocs.org/user_builds/ibex-core/checkouts/2130" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ibex-core/envs/2130/lib/python3.11/site-packages/sphinx/registry.py", line 438, in load_extension
    metadata = setup(app)
               ^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/ibex-core/envs/2130/lib/python3.11/site-packages/sphinxcontrib/applehelp/__init__.py", line 230, in setup
    app.require_sphinx('5.0')
  File "/home/docs/checkouts/readthedocs.org/user_builds/ibex-core/envs/2130/lib/python3.11/site-packages/sphinx/application.py", line 393, in require_sphinx
    raise VersionRequirementError(version)
sphinx.errors.VersionRequirementError: 5.0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ibex-core/envs/2130/lib/python3.11/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/ibex-core/envs/2130/lib/python3.11/site-packages/sphinx/application.py", line 219, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ibex-core/envs/2130/lib/python3.11/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ibex-core/envs/2130/lib/python3.11/site-packages/sphinx/registry.py", line 441, in load_extension
    raise VersionRequirementError(
sphinx.errors.VersionRequirementError: The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.

Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```
I don't know if we can just update the Sphinx version but someone should definitely look into this.

**Comment by humitos** [comment]
This was reported in Sphinx repository at https://github.com/sphinx-doc/sphinx/issues/11890. You can find some help there.
